### ISSUE TITLE
Compatibility with proton GE 

### ISSUE THREAD

**Issue by thibaultmol** [caverym/Proton-Caller#12]
I don't think it works with custom versions of proton yet?
For example, I installed Proton  GloriousEggroll edition (lazily using the aur build on my manjaro install)
https://aur.archlinux.org/packages/proton-ge-custom-bin/
But doesn't seem like it detects it correctly.
Also, the folder where it puts that custom version in is: 
usr/share/steam/compatibilitytools.d/proton-ge-custom

**Comment by caverym** [comment]
Two options I will try is using custom mode like 
`proton-call -c /usr/share/steam/compatibilitytools.d/proton-ge-custom/foo.exe`
Tell me what happens

**Comment by thibaultmol** [comment]
`proton-call -c /usr/share/steam/compatibilitytools.d/proton-ge-custom/`
worked.
So I guess adding a a thing that detects it and allows you to use the version instead "6.1-GE-2"?

**Comment by caverym** [comment]
Eventually. Currently the proton detection just takes a string and adds `/proton` to it.. I plane on make it much smarter to detect. I have ideas for it, mainly to read the directory and pick whichever contains a given string should work. The best part of software is that it can always be improved. Thank you!

**Comment by caverym** [comment]
I just pushed a commit which would allow this to work better. Hopefully you find it useful
