### ISSUE TITLE
Ability to just use the most recent version of proton?

### ISSUE THREAD

**Issue by thibaultmol** [caverym/Proton-Caller#13]
I don't know if it's possible, but ideally I'd like to just launch an application with the latest version of proton

**Comment by caverym** [comment]
This is planned, I'm not going to have much time to do a release until this weekend—expect it then

**Comment by caverym** [comment]
As of commit e0467c3, this is now possible.
`proton-call foo.exe` works and (currently) will launch `foo.exe` with Proton 5.13.
