### ISSUE TITLE
Request: A ui or a fork with a ui

### ISSUE THREAD

**Issue by Nateaaaaaaaaaaaaaaaaaaaa** [caverym/Proton-Caller#16]
#

**Comment by caverym** [comment]
A UI? Yes, of course. `.desktop` files. I have it in the [README](https://github.com/caverym/proton-caller#space-engine-example), explains how you can create a desktop link file which will launch Proton Caller with the program you put in the file.

**Comment by benthetechguy** [comment]
And if you want something like a launcher, programs like Lutris already exist; that's not what this project aims to be.
