### ISSUE TITLE
Compile for lower glibc versions

### ISSUE THREAD

**Issue by BlockListed** [caverym/Proton-Caller#17]
The standard 2.33 glibc version is not available on lots of distros. How would I compile for glibc 2.32?

**Comment by caverym** [comment]
Have you tried compiling it on a 2.32 system?

**Comment by benthetechguy** [comment]
That specific version suggests to me you're using Ubuntu 20.10, since it's the only popular distro that uses that particular version; all the others are either 2.31 or 2.33. I compiled proton-caller in a groovy chroot for you, here is [the executable](https://github.com/caverym/Proton-Caller/files/6046097/proton-call.tar.gz).

Compiling it yourself is really not that hard; the toughest part is getting rust installed on a debian-based distro.

**Comment by benthetechguy** [comment]
By the way, i'd like to mention that I would be willing to package proton-caller for debian-based distros if I can figure it out.

**Comment by caverym** [comment]
> By the way, i'd like to mention that I would be willing to package proton-caller for debian-based distros if I can figure it out.

Package it for `dpkg` **and** `rpm` ???? PLease?D?FASDF? lmao. They are all overly complicated packaging systems.

**Comment by caverym** [comment]
I can confirm it compiles with 2.32, also. And cross-compiles for aarch64 now.

**Comment by benthetechguy** [comment]
Debian packaging is finished, RPM I have absolutely no idea how to do or even any experience even using an rpm distro.

**Comment by logix2** [comment]
Compiling it on an older version will make it work on most distros. E.g. building it on Ubuntu 18.04 (or, if not possible, 20.04).

**Comment by caverym** [comment]
I don't compile for older versions because my systems all use the latest software, @benthetechguy has compiled it for older versions and packaged for Ubuntu, which will be added to the latest release eventually. You could, while you wait, compile it yourself just using `cargo b`

**Comment by logix2** [comment]
I can compile it, but I wanted to write about it on my blog, and there are many users who skip anything that requires compiling. So I'll wait for that package compiled for older versions (a generic binary would have been better... as it can be used on other Linux distributiona but I'll take what I can get :-) ). Thanks!

**Comment by caverym** [comment]
> I can compile it, but I wanted to write about it on my blog, and there are many users who skip anything that requires compiling. So I'll wait for that package compiled for older versions (a generic binary would have been better... as it can be used on other Linux distributiona but I'll take what I can get :-) ). Thanks!

It is being compiled for more than just Ubuntu. I personally don't use anything other than Arch, so I can't do it myself.
