### ISSUE TITLE
Error when trying to install .exe/.msi file

### ISSUE THREAD

**Issue by TheLumbee** [caverym/Proton-Caller#18]
Following error display in terminal:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/proton.rs:82:45
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Not sure what file/directory it's looking for.
proton.conf was created correctly.

**Comment by caverym** [comment]
Can I see the command you put in which gives you this error? This error is received when it cannot find the `common` directory you set in the config.

**Comment by caverym** [comment]
I have just pushed a commit that creates a better error message (prevents a panic) when the common directory doesn't exist. Something I stupidly overlooked.

**Comment by TheLumbee** [comment]
The command is the same format as in the readme. I've tried both:

`proton-call 5.13 NinjaInstall.msi` & `proton-call NinjaInstall.msi`

**Comment by TheLumbee** [comment]
FIXED!

I was not installing Proton correctly on my machine. I'll close this issue.
