### ISSUE TITLE
Starting .lnk files

### ISSUE THREAD

**Issue by Kho-Dialga** [caverym/Proton-Caller#19]
Hello everyone, I've been using this to play a bit of Touhou patched with thcrap. I recall being able to launched the .lnk files generated by it with proton-call without any problem. But today I tried playing some and the games didn't launch. Am I launching said .lnk files incorrectly?

**Comment by caverym** [comment]
proton-call doesn't generate link files, you can create your own `.desktop` file to launch software using proton-call.
