### ISSUE TITLE
thread 'main' panicked at 'no entry found for key', src/bin/proton-call.rs:70:20

### ISSUE THREAD

**Issue by jobrum** [caverym/proton-caller#29]
Trying to run a game via proton-call but getting the following errors.

$ RUST_BACKTRACE=full proton-call -p 5.13
thread 'main' panicked at 'no entry found for key', src/bin/proton-call.rs:70:20
stack backtrace:
   0:     0x560adad87678 - std::backtrace_rs::backtrace::libunwind::trace::h7f0f727c679b121e
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560adad87678 - std::backtrace_rs::backtrace::trace_unsynchronized::h27b8207adc787597
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560adad87678 - std::sys_common::backtrace::_print_fmt::h18c4a15687f3f453
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560adad87678 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7077f94cc0b2a619
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560adad6a8af - core::fmt::write::hd1fcbdc89ccede50
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1096:17
   5:     0x560adad872e5 - std::io::Write::write_fmt::h3030f95a96ab63e0
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/io/mod.rs:1568:15
   6:     0x560adad9abaa - std::sys_common::backtrace::_print::hce920b6e4ede72f2
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560adad9abaa - std::sys_common::backtrace::print::h63694f3a744810f6
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560adad9abaa - std::panicking::default_hook::{{closure}}::h2f22ad38e825d5e1
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:208:50
   9:     0x560adad9abaa - std::panicking::default_hook::hc0998dccd7f968a3
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:225:9
  10:     0x560adad9abaa - std::panicking::rust_panic_with_hook::h618d5ded1dbe5ea3
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:591:17
  11:     0x560adad885c8 - std::panicking::begin_panic_handler::{{closure}}::h64f3a351a9df3931
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:497:13
  12:     0x560adad8853c - std::sys_common::backtrace::__rust_end_short_backtrace::hf7a8c7450479e920
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x560adad9804d - rust_begin_unwind
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
  14:     0x560adad6a5e0 - core::panicking::panic_fmt::hac8d59bba791921f
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
  15:     0x560adad63f32 - core::option::expect_failed::ha271250dcd72abbd
                               at /build/rustc-wdnoYU/rustc-1.51.0+dfsg1+llvm/library/core/src/option.rs:1292:5
  16:     0x560adad5a15f - <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index::h74a93289b2ebc5a1
  17:     0x560adad5ed4d - proton_call::proton_caller::hdc69b3b37678fd52
  18:     0x560adad5b531 - proton_call::main::hab0e63057c64b408
  19:     0x560adad5a164 - std::sys_common::backtrace::__rust_begin_short_backtrace::hade4a0d077be9449
  20:     0x560adad60ddc - main
  21:     0x7f9206ba2565 - __libc_start_main
  22:     0x560adad5a07e - _start
  23:                0x0 - <unknown>

**Comment by godotdot** [comment]
Not a proton-caller dev, but I think that's due to your config not having a value for steam.

Just like when you set the paths for data and common, you need to give a path for steam.
Probably something like:
steam = "/home/yourusername/.steam/steam/"

I don't think this is in the install docs, at least, I didn't notice it.

**Comment by caverym** [comment]
I just updated the readme. I've been slow to update this because I have school and work. Updates are coming soon, though
