### ISSUE TITLE
proton-caller seems to be using steam instead of common for proton path

### ISSUE THREAD

**Issue by yaccin** [caverym/proton-caller#30]
I have set my proton.conf file to:

```
data = "/home/auryn/Documents/Proton/env/"
steam = "/home/auryn/.steam/steam/"
common = "/home/auryn/.steam/steam/steamapps/common/"
```

as per the instructions on https://github.com/caverym/proton-caller, however, this causes the error: 
`error: /home/auryn/.steam/steam//Proton 3.7/proton not found!`

If i change the config to:

```
data = "/home/auryn/Documents/Proton/env/"
steam = "/home/auryn/.steam/steam/steamapps/common/"
```
it seems to work however.

**Comment by caverym** [comment]
Yep. This one is already fixed, just not released yet. I've been working on Jargon and implementing jargon in Proton Caller for some time, but I'll make a release with this fix in a few hours.

**Comment by caverym** [comment]
please try commit d014aba4f102e2fad39bc1a9321c34d0372dd74f and see how it works for you

**Comment by yaccin** [comment]
sorry it took so long to get back, but yes, it seems to be working now!
