### ISSUE TITLE
thread 'main' panicked at 'no entry found for key'

### ISSUE THREAD

**Issue by MichaelBest01** [caverym/proton-caller#35]
I set up my config and got this error
```
thread 'main' panicked at 'no entry found for key', src/bin/proton-call.rs:63:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
My config is 
```
data = "/home/michaelbest01/Documents/Proton/env/"
common = "/home/michaelbest01/.steam/steam/steamapps/common/"
```

**Comment by caverym** [comment]
Please try the 3.0.0 pre-release

**Comment by MichaelBest01** [comment]
I updated to the pre-release and changed the config to this. Now it works just fine.
`
steam = "/home/michaebest01/.steam/steam/"
data = "/home/michaelbest01/Documents/Proton/env/"
common = "/home/michaelbest01/.steam/steam/steamapps/common/"
`
