### ISSUE TITLE
Current progress

### ISSUE THREAD

**Issue by caverym** [caverym/Proton-Caller#4]
I am still working on Proton Caller but all offline. I am reworking the system that manages command line arguments and adding a system of default values. If you have any questions or recomendations for Proton Caller, you can comment them here for the future.

**Comment by guglovich** [comment]
I am interested in how to make a point in Thunar, what launch command to specify there. And in the future, I would like to see it embedded in the explorer, to be the default program instead of Wine.

**Comment by aslok** [comment]
I play Snowrunner from Epic Games Launcher with this tool, thank you for your work!
Have one issue with cmd args for EpicGamesLauncher.exe - need to pass -opengl and -SkipBuildPatchPrereq but no way to do it with Proton-Caller or I dont know how to use it.

So my current code:
$ cat .local/share/applications/snowrunner-1.desktop 
[Desktop Entry]
Exec=proton-call 5.13 EpicGamesLauncher.bat
Icon=snowrunner
Name=Snowrunner
Path=.steam/steam/steamapps/compatdata/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win64
StartupNotify=true
Type=Application
$ cat '.steam/steam/steamapps/compatdata/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.bat'
@ECHO OFF
@EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
$

**Comment by caverym** [comment]
> I play Snowrunner from Epic Games Launcher with this tool, thank you for your work!
> Have one issue with cmd args for EpicGamesLauncher.exe - need to pass -opengl and -SkipBuildPatchPrereq but no way to do it with Proton-Caller or I dont know how to use it.
> 
> So my current code:
> $ cat .local/share/applications/snowrunner-1.desktop
> [Desktop Entry]
> Exec=proton-call 5.13 EpicGamesLauncher.bat
> Icon=snowrunner
> Name=Snowrunner
> Path=.steam/steam/steamapps/compatdata/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win64
> StartupNotify=true
> Type=Application
> $ cat '.steam/steam/steamapps/compatdata/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.bat'
> @echo OFF
> @EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
> $

I know that passing arguments is needed. I'm working on that too and everything will hopefully be in the next update. Thank you ! @aslok

**Comment by caverym** [comment]
> I play Snowrunner from Epic Games Launcher with this tool, thank you for your work!
> Have one issue with cmd args for EpicGamesLauncher.exe - need to pass -opengl and -SkipBuildPatchPrereq but no way to do it with Proton-Caller or I dont know how to use it.
> 
> So my current code:
> $ cat .local/share/applications/snowrunner-1.desktop
> [Desktop Entry]
> Exec=proton-call 5.13 EpicGamesLauncher.bat
> Icon=snowrunner
> Name=Snowrunner
> Path=.steam/steam/steamapps/compatdata/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win64
> StartupNotify=true
> Type=Application
> $ cat '.steam/steam/steamapps/compatdata/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.bat'
> @echo OFF
> @EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
> $

Released 2.0, it allows you pass arguments to the windows executable :) Thank you so much for using the Proton Caller
