### ISSUE TITLE
proton-call checks for config before anything else, making --version and --help fail

### ISSUE THREAD

**Issue by benthetechguy** [caverym/proton-caller#42]
Since no man page is provided, I have to use `help2man` (program that generates a man page based on a program's `--help` output) for the Debian package. The only problem with this is that in the new 3.0.0 pre-release, basic commands like `--help` and `--version` won't run without a config file.

```
ben@deb-builder:~/proton-caller$ ./proton-call --help
proton-call: error: 'No such file or directory (os error 2)' when opening config
ben@deb-builder:~/proton-caller$ ./proton-call --version
proton-call: error: 'No such file or directory (os error 2)' when opening config
```

**Comment by caverym** [comment]
I will change this, but 3.0.0 is not ready to be packaged into repos yet.

**Comment by benthetechguy** [comment]
Not planning to put this in any repos, just adding binaries to the GitHub release and making sure it builds the Deb properly before the full release. Thank you for fixing this 👍
