### ISSUE TITLE
Unable to read VR Path Registry

### ISSUE THREAD

**Issue by zinzui12345** [caverym/proton-caller#44]
> khairul@programmerindonesia44:$ proton-call -r gta_sa.exe -c /home/khairul/.steam/debian-installation/steamapps/common/Proton\ -\ Experimental/
Running Proton Custom for gta_sa.exe
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath

i try to run non-steam gta san andreas, every time it fails and displays that message but the game is not vr game

System: Ubuntu 21.04
Kernel: 5.11.0-38-generic

**Comment by caverym** [comment]
May I see the message it gives?

**Comment by zinzui12345** [comment]
> May I see the message it gives?

![image](https://user-images.githubusercontent.com/48501018/143773522-f0f77b75-c5db-4b57-90e3-91ac134b8916.png)

**Comment by zinzui12345** [comment]
> May I see the message it gives?

![image](https://user-images.githubusercontent.com/48501018/143773808-0f36e80a-e7b0-4b37-bd79-98f3b61efa68.png)

sometimes the screen flickers and the game immediately stops after the message appears
I've also tried running it directly with wine and the result is normal but the performance is very slow

**Comment by caverym** [comment]
Have you tried proton 3.0.x?
