### ISSUE TITLE
A way to write detailed logfiles for proton.

### ISSUE THREAD

**Issue by Realitaetsverlust** [caverym/proton-caller#53]
I'm currently trying to run an old game from GOG through proton-caller. I've only had mediocre success for now, with 6.3 I get to watch the intro videos, with experimental it doesn't even launch. I do not get any detailed error reports at all, sometimes I don't get any logs at all.

Steam is saving detailed logs to steam-{game-id}.txt in the home directory. If possible to access this log writing mechanic, an optional parameter that enables proton-caller to write a logfile into the game or prefix directory would be amazing as it would really help debugging and troubleshooting games.

**Comment by caverym** [comment]
Try the `--log` argument.

**Comment by Realitaetsverlust** [comment]
I tried that, however, the output doesn't change.

With `--log`:
```
$ proton-call --log -p experimental -r popTBUW.exe
warning: using default common
Running Proton Experimental for popTBUW.exe
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

Without `--log`:
```
$ proton-call -p experimental -r popTBUW.exe
warning: using default common
Running Proton Experimental for popTBUW.exe
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

There is also nothing written into my home directory.

**Comment by caverym** [comment]
I have checked to make sure the correct variable is set inside proton to produce logs, it is, but neither do I get logs. This is an issue with Proton.
