### ISSUE TITLE
Proton: Error while copying to .../_nvngx.dll : No such file or directory

### ISSUE THREAD

**Issue by artik** [caverym/proton-caller#54]
When trying to launch a .exe using `proton-caller`, I have this error:

```
proton-call -r '/home/artik/setup.exe' 
Running Proton 6.3 for /home/artik/setup.exe
Proton: Error while copying to "/home/artik/.proton//Proton 6.3/pfx/drive_c/windows/system32/_nvngx.dll": No such file or directory
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
wine: Unhandled exception 0x0eedfade in thread 110 at address 7B0110D7 (thread 0110), starting debugger...
Process of pid=010c has terminated
No process loaded, cannot execute 'echo Modules:'
Cannot get info on module while no process is loaded
No process loaded, cannot execute 'echo Threads:'
process  tid      prio (all id:s are in hex)
```

And here is my `proton.conf`:

```
data = "/home/artik/.proton/"
steam = "/home/artik/.steam/steam/"
common = "/home/artik/.steam/steam/steamapps/common/"
```

It looks like it's related to this bug:
https://github.com/ValveSoftware/Proton/issues/4381

2 things to know: line 3, of my log I can see a double `//` don't know if it affect the result.
Also, I have in the `system32` folder a `nvngx.dll`, but without the underscore. I tried to copy/rename in `_nvngx.dll`, but same error

Using:
 - OS: Linuxmint 20.3
 - Chrome stable 97.0.4692.71

**Comment by caverym** [comment]
I'll add 5.13+ to run in the runtime in pc 3.1+ thank you

**Comment by caverym** [comment]
try using commit 253ac93 if possible

**Comment by caverym** [comment]
Proton 3.1.0 should have fixed this issue. Reopen if it continues.
