### ISSUE TITLE
wine: Using setpriority to control niceness in the [-19,19] range

### ISSUE THREAD

**Issue by daybreak1024** [caverym/proton-caller#56]
use 
````
$ sudo proton-call -r project.exe
````
log is:
````
Running Proton 6.3 for /home/test/Documents/app/project.exe
esync: up and running.
wine: Using setpriority to control niceness in the [-19,19] range
````
the app is not work.

Looking forward to your reply！

**Comment by yellowsink** [comment]
Those look like standard, very normal wine logs to me, not an issue as far as I am aware?

**Comment by benthetechguy** [comment]
Why are you running proton-call as root, anyway?

**Comment by caverym** [comment]
I might add something to make it refuse to run as root.

**Comment by caverym** [comment]
but also, @yellowsink is right. This isn't something to worry about as far as I've read

**Comment by caverym** [comment]
(it is also a proton thing, not at all related to proton-caller) ;)
