### ISSUE TITLE
Proton not found

### ISSUE THREAD

**Issue by Hhk78** [caverym/proton-caller#57]
I installed an old game with the DVD. But when trying to run the installed game with proton, I get the following error: 
`[h@hh Need for Speed Carbon]$ proton-call -p 6.3-8 -r nfs.exe
proton-call: cannot find Proton: Proton 6.3 does not exist
`
Proton is installed on my system.
`[h@hh Need for Speed Carbon]$ proton -h

USAGE:  proton executable.exe
        proton [mode]  executable.exe
        proton [appid] executable.exe
        proton [--environment|-e] [--help|-h]

ENV:    STEAM_COMPAT_DATA_PATH
        SteamAppId
        SteamGameId

Just call this proton launcher script with your app as the only argument
to run it with the default prefix
/home/h/.local/share/proton-pfx/0 and default mode "waitforexitandrun".

_mode_
You can change the mode of operation by specifying it as the first argument.
Possible values are: waitforexitandrun, run, getcompatpath, getnativepath

_appid_
Protonfixes uses three environment variables to determine the application to
run fixes for. The env STEAM_COMPAT_DATA_PATH points to the wine prefix and
usually includes the AppId. If the env SteamAppId (or SteamGameId) is set, it
takes precedence as the AppId used.

As proton itself needs the env STEAM_COMPAT_DATA_PATH, the default prefix
/home/h/.local/share/proton-pfx/0 is used when it is not set or empty.
An AppId given by env SteamAppId will alter this path accordingly.

Provide "appid" as an argument instead of "mode" to change the AppId regardless
of the env vars. In this case, the mode defaults to "waitforexitandrun".
Useable for "appid": see https://steamdb.info/apps/

Note that the env SteamGameId is not set by this launcher script in any case.
This env is evaluated by steam executables inside the prefix. Set it yourself
as you see fit.

To see the current ENV when this script is called, use "-e" the switch.

`
At least it gives information when you type it. :D
Sorry for english. I use translate. :)

**Comment by caverym** [comment]
the commands `proton-call` and `proton` are different. This repository is for `proton-call`, I cannot provide support for `proton`

**Comment by Hhk78** [comment]
> the commands `proton-call` and `proton` are different. This repository is for `proton-call`, I cannot provide support for `proton`

I know. But it can't summon the proton, that's the problem.

**Comment by caverym** [comment]
Where is Proton installed?
Where is Steam installed?
What are the contents of your config file?

**Comment by crthpl** [comment]
I also have this problem, and I think the problem is that steam now stores proton in `steamapps/common/Proton - Experimental`  instead.

**Comment by caverym** [comment]
That is handled by Proton Caller already

**Comment by caverym** [comment]
@Hhk78 I'm going to check on one last time. Make sure you run the latest version of proton-caller and your configs are set correctly. I'll close this soon.
