### ISSUE TITLE
No such file or directory: .../Proton 6.3/dist/bin/wine64

### ISSUE THREAD

**Issue by davidak** [caverym/proton-caller#59]
**Describe the bug**
The program fails to run with this issue:

```
[davidak@gaming:~/Downloads/Grey_Box_Testingv0_1_5]$ proton-call -r Grey-Box-Testing.exe 

________Proton________
Traceback (most recent call last):
  File "/home/davidak/.steam/steam/steamapps/common/Proton 6.3/proton", line 1294, in <module>
    rc = g_session.run()
  File "/home/davidak/.steam/steam/steamapps/common/Proton 6.3/proton", line 1256, in run
    rc = self.run_proc([g_proton.wine64_bin, "steam"] + sys.argv[2:] + self.cmdlineappend)
  File "/home/davidak/.steam/steam/steamapps/common/Proton 6.3/proton", line 1241, in run_proc
    return subprocess.call(args, env=local_env, stderr=self.log_file, stdout=self.log_file)
  File "/nix/store/19j43hyh37jqnn9l7rg6shk5barbn209-python3-3.9.6/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/nix/store/19j43hyh37jqnn9l7rg6shk5barbn209-python3-3.9.6/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/19j43hyh37jqnn9l7rg6shk5barbn209-python3-3.9.6/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/davidak/.steam/steam/steamapps/common/Proton 6.3/dist/bin/wine64'
______________________

error: Proton exited with error
```

The error message is a lie. The file does exist!

```
[davidak@gaming:~/Downloads/Grey_Box_Testingv0_1_5]$ ll '/home/davidak/.steam/steam/steamapps/common/Proton 6.3/dist/bin/wine64'
-rwxr-xr-x 1 davidak users 16736 Dec  6 12:05 '/home/davidak/.steam/steam/steamapps/common/Proton 6.3/dist/bin/wine64'
```

proton.conf
```
data = "/home/davidak/Documents/Proton/env"
steam = "/home/davidak/.steam/steam"

# optional
common = "/home/davidak/.steam/steam/steamapps/common"
```

**To Reproduce**
1. Download game from https://samhogan.itch.io/grey-box-testing
2. Try to run it
3. Get error

**Expected behavior**
Game just works

**Desktop (please complete the following information):**
 - OS: NixOS 21.11.335443.e84444b14cc
 - Browser Chrome
 - Version 97.0.4692.99

**Additional context**
Using program from nixpkgs in version [2.3.2](https://github.com/caverym/proton-caller/releases/tag/2.3.2): https://search.nixos.org/packages?channel=21.11&show=proton-caller&from=0&size=50&sort=relevance&type=packages&query=proton

**Comment by davidak** [comment]
Yes, that's the issue!

On NixOS we have a wrapper tool called `steam-run` that runs applications in the same environment steam would run games. When i call proton using it, the game works.

```
[davidak@gaming:~/Downloads/Grey_Box_Testingv0_1_5]$ STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/steam" STEAM_COMPAT_DATA_PATH="/home/davidak/Documents/Proton/env" steam-run /home/davidak/.steam/steam/steamapps/common/Proton\ -\ Experimental/proton run Grey-Box\ Testing.exe 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

**Comment by caverym** [comment]
Yep. This is a coming feature. You can see in recent commits. Progress has been slow due to prior obligations. However, You can expect it before March.

**Comment by davidak** [comment]
Great. Thanks for your work!

**Comment by caverym** [comment]
Just letting you know that 3.1.0 uses the Runtime now, this should be fixed

**Comment by pmarreck** [comment]
@davidak I'm running Steam in a flatpak on NixOS. There's no `steam-run` available in my PATH (I'm actually running a search for it elsewhere now), but might encountering this same bug also be explained by this in 2023? Everything I have is up-to-date.

**Comment by davidak** [comment]
@pmarreck steam-run is a nixos package which is a wrapper for the LSB environment the nixos steam package uses to run games. The Flatpak package is something completely different.
