### ISSUE TITLE
proton-call: error: proton.conf does not exist

### ISSUE THREAD

**Issue by jJit0** [caverym/Proton-Caller#6]
Hi,

When I type
`proton-call 5.13 tinfoleak.exe` or `proton-call -c '~/.steam/steam/steamapps/common/Proton\ 5.13/' tinfoleak.exe`

I get this error: `proton-call: error: proton.conf does not exist`

Any ideas ?

**Comment by caverym** [comment]
Hey! Sorry, I was actually just adding configuration files today, so I couldn't get the documentation into place (until just now). Sorry about that. All you do is create a config file at `~/.config/proton.conf` and populate it like this: (but with your own paths)
```
data = "/home/avery/Documents/Proton/env/"
common = "/home/avery/.steam/steam/steamapps/common/"
```

**Comment by jJit0** [comment]
Ok, I actually found it before you send your comment.

As I installed proton-caller via cargo: `cargo install --git https://github.com/caverym/Proton-Caller.git` the proton.conf was actually in `$CARGO_HOME/git/checkouts/proton-caller-f141830b0eaa4c1b/bf86680/proton.conf`

One thing though, I know where the common dir is `common = "~/.steam/steam/steamapps/common/` but I don't know where data dir `data = "~/Documents/Proton/env/` I don' it have this in my ~

**Comment by caverym** [comment]
The data directory can be any random directory. Mike's just an example. The directory is used by proton itself to set-up win inside.

**Comment by jJit0** [comment]
Oh okay, it's to store proton data.

Does it work with old versions of proton, like 5.0 ?

**Comment by caverym** [comment]
Any version that's installed will work, you just make sure you have that version installed to the directory `common`. You put any version you want before the executable, then any arguments to pass to the executable after:

`proton-call 4.13 foo.exe --vulkan`
