### ISSUE TITLE
Proton-call exiting with code 5 on some games if command is run via .desktop shortcut

### ISSUE THREAD

**Issue by revix-0** [caverym/proton-caller#60]
**Describe the bug**
Proton-call  crashes while running games via shortcuts

**To Reproduce**
1. make a .desktop file
2. put these entries:
  [Desktop Entry]
Version=1.0
Exec=sh -c "proton-call -r /path/to/game/file.exe/"
Path=/where/you/are/storing/.desktop/file
Terminal=true
Type=Application
4. run the .desktop and the game will crash

Tested on games:
-Crash bandicoot N.Sane Trilogy (runs fine with proton-call/wine in terminal in the same folder, yes i've checked for spaces in the .desktop)

-BFBC2 (instantly closes terminal, runs on proton/wine)

-Blur (same as NST Behavior)

**Expected behavior**
The game should open normally like when running the command via CLI.

**Screenshots**
![image](https://user-images.githubusercontent.com/30447649/157020235-43d84a0b-f4a1-43e2-905f-415fc02310f4.png)
for NST case.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Firefox
 - Version lastes

**Additional context**
//

**Comment by caverym** [comment]
Can you try and provide a log file from proton so I can understand what is happening? The error occurs inside Proton and not proton-caller.
