### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Mart-Bogdan** [caverym/proton-caller#69]
**Is your feature request related to a problem? Please describe.**
I would like being able to install using cargo.

**Describe the solution you'd like**
`cargo install proton-caller`

**Describe alternatives you've considered**
You are suggesting to isntall from GIT, but that's not so convenient.

**Additional context**
```
$ cargo install proton-caller                                                                                                                                                                                     
    Updating crates.io index
error: could not find `proton-caller` in registry `crates-io` with version `*`
```

**Comment by caverym** [comment]
It is "proton-call" on crates
