### ISSUE TITLE
MSFS: Getting FENIX A320 installed on Fedora with Proton

### ISSUE THREAD

**Issue by rrllrr** [caverym/proton-caller#73]
Hi,

I was trying to install the FENIX A320 for the Microsoft Flight Simulator but I got some error messages while trying it. I used the following command to get the exe file to run:
`STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/raphael/.local/share/Steam" \
STEAM_COMPAT_DATA_PATH="/home/raphael/.local/share/Steam/steamapps/compatdata/1250410" \
/home/raphael/.local/share/Steam/compatibilitytools.d/proton_tkg_experimental.bleeding.edge.7.0.27438.20221022/proton \
run \
FenixSimA320-1.0.6.146.exe`

And these are the error messages I get:
`fsync: up and running.`
`wine: RLIMIT_NICE is <= 20, unable to use setpriority safely`
`wine: failed to start L"C:\\Program Files (x86)\\Steam\\steam.exe"`
`Es konnte keine Anwendung gestartet werden, oder es ist keine Anwendung mit der angegebenen Datei verknüpft.`
`ShellExecuteEx fehlgeschlagen: Prozedur nicht gefunden.`

What can I do to solve this problem?

**Comment by caverym** [comment]
You closed this, I'm guess you got it installed ?

**Comment by rrllrr** [comment]
No. I accidently created a new issue. It was transfered to this one:
https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1399248995

**Comment by rrllrr** [comment]
@caverym Do you have any idea how I could solve it?
